apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: okd-coreos-prod
spec:
  params:
  - name: branch
    value: $(body.params.branch)
  - name: version
    value: $(body.params.version)
  - name: release-stream
    value: $(body.params.release-stream)
  - name: rpm-artifacts-image
    value: $(body.params.rpm-artifacts-image)
  - name: tag-latest
    value: $(body.params.tag-latest)
  - name: claimname
    value: $(body.params.claimname)
