apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-scos-4.14-pv
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: pipeline-scos-4.14-pvc
    namespace: okd-coreos
  storageClassName: local
  local:
    path: /dev/sdc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host-192-168-111-83
