kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: okd-artifacts
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "4.16"
      from:
        kind: DockerImage
        name: registry.ci.openshift.org/origin/scos-4.16:artifacts
      importPolicy:
        scheduled: true
    - name: "4.17"
      from:
        kind: DockerImage
        name: registry.ci.openshift.org/origin/scos-4.17:artifacts
      importPolicy:
        scheduled: true
